name: Project build

on: push

jobs:
  build:
    paths:
    - 'src/**'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install
        run: sudo apt-get update && sudo apt-get install -y build-essential ccache curl nasm genisoimage qemu qemu-kvm mtools
      - name: Get cross compiler
        id: cache-cross
        uses: actions/cache@v1
        with:
          path: cross
          key: ${{ runner.os }}-cross
      - name: Build cross compiler
        if: steps.cache-cross.outputs.cache-hit != 'true'
        run: |
          sudo apt-get install -y bison flex libgmp3-dev libmpc-dev libmpfr-dev texinfo libcloog-isl-dev libisl-0.18-dev curl
          sh run cross
      - name: Build
        run: sh run build
      - name: Test install
        run: sh run image
