name: Project build and nightly release

on:
  schedule:
  - cron: "0 2 * * 0"
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install
      run: sudo apt-get update && sudo apt-get install -y build-essential bison flex libgmp3-dev libmpc-dev libmpfr-dev texinfo libcloog-isl-dev libisl-dev curl nasm grub qemu qemu-kvm
    - name: Make
      run: make cross build
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
          files: build/melvix.iso
          name: Melvix Nightly Release
          prerelease: 1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
