name: Weekly project build and release

on:
  schedule:
    - cron: "0 2 * * 0"
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install
        run: sudo apt-get update && sudo apt-get install -y build-essential bison flex libgmp3-dev libmpc-dev libmpfr-dev texinfo libcloog-isl-dev libisl-0.18-dev curl nasm grub2 qemu qemu-kvm mtools
      - name: Build
        run: make cross build
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/melvix.iso
          name: Melvix Weekly Release
          prerelease: 1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
